### ISSUE TITLE
No save on certain markers

### ISSUE THREAD

**Issue by stumpdk** [jacobandresen/TagMap#14]
Some markers won't save name and content while editing.

**Comment by jacobandresen** [comment]
it looks like it is related to "name" and "content" missing when starting. I'll have to setup a backend test instance to track this.

**Comment by jacobandresen** [comment]
I have a local test instance now. I'll try to reproduce it locally

**Comment by jacobandresen** [comment]
Maybe this is related to #6 . We do not currently refresh the  layers on the map after editing or deleting it.

**Comment by jacobandresen** [comment]
We have fixed the following after this issue has been reported:
- id is now not editable on the client
- Records with empty "name" and "content" can now be deleted (#9)

**Comment by jacobandresen** [comment]
Issue #6 is now fixed.

**Comment by jacobandresen** [comment]
Looks like the issue is fixed with #20
