### ISSUE TITLE
Saving data on error

### ISSUE THREAD

**Issue by stumpdk** [jacobandresen/TagMap#20]
If a marker is created without a tag value, the user is alerted, but somehow, the tag data is saved anyway.

**Comment by stumpdk** [comment]
This is what happens:
1) The user tries to put a marker without a tag.
2) The user fills out the tag and places the marker again
3) All markers, including the ones without tags, are saved

**Comment by jacobandresen** [comment]
we had some leftover code lying around  that used to handle edit/delete events directly from the map. I removed it in favor of the code for the save and delete buttons. This should fix the error for now.
