### ISSUE TITLE
Selected marker should be highlighted

### ISSUE THREAD

**Issue by stumpdk** [jacobandresen/TagMap#22]
When selecting a marker, the given marker should be highlighted, either by using another style or another kind of marker.

**Comment by stumpdk** [comment]
An early version of displaying selected markers is now implemented.
For this to work properly, the markers should consist of icons, not circles, as it is now. I'm not sure how much extra work this will require.

**Comment by stumpdk** [comment]
The feature works great, but should work with markers consisting of images, not geometric points. Any chance of implementation?

**Comment by jacobandresen** [comment]
Do you want a marker containing  an image ? What do you want when it's a line/polygon  "E.g : a route" - a marker on the middle perhaps?

**Comment by stumpdk** [comment]
When it's geometric features other than points, nothing should be done at this point.
The markers should be an image, changing when selected, and with images depending on the tag type.

**Comment by jacobandresen** [comment]
We now place a marker on the selected spot , using a custom icon given by the tag type
