### ISSUE TITLE
marker links

### ISSUE THREAD

**Issue by jacobandresen** [jacobandresen/TagMap#25]
It should possible to navigate to a new marker from the marker text.

There should be a link in the rendered html . When the user clicks the link the map should zoom into the new marker - and the text area should be updatde with the text from the new marker.

One way to do it would be by using HTML5 datatags and injecting the link event handler code after rendering the marker.

**Comment by jacobandresen** [comment]
#11 should be solved while/before doing this.

**Comment by stumpdk** [comment]
This is seen as a critical feature in the project. Any expectations on implementation?

**Comment by jacobandresen** [comment]
It should allready be on the master branch:
https://github.com/jacobandresen/TagMap/commit/043f2a1082975f4af9c7f685122469df911ab58b

You can store links in the text in the editor like this: 
  <a href="#" data-tag="39">link til nummer 39</a>   (click edit to see the html)

Note that #11 currently is not working .

**Comment by stumpdk** [comment]
Links to markers works. But the information for the new selected marker is not shown in the infoDivs.
At the same time, there is a more general problem: If a link point to a marker not in the current selection, the marker is not selected (as there is no marker to select).

**Comment by jacobandresen** [comment]
note that infoDivs are updated in show.html . I changed the taglink syntax to the following:

  <a href="#" data-id="39" data-tags="detandettag,dettredjetag">link til nummer 39</a> (click edit to see html)

Now the id is stored in data-id . "tags" is stored in data-tags. The value in "data-tags" should contain a value for "data-id".

**Comment by jacobandresen** [comment]
I solved " If a link point to a marker not in the current selection, the marker is not selected (as there is no marker to select)."  by adding a "data-tags" in the taglink. We now restart the search using the given tags and the given id. In this way we can reach all markers.

**Comment by stumpdk** [comment]
Is it possible to avoid using the data-tags-information by simply loading just the selected tag (that is, getting the tag by id from the api)?

**Comment by stumpdk** [comment]
After a talk with the project leader, it is clear that the markers should be loaded by id, and by tag. So the marker should be loaded by id, and should be the only extra marker shown.

**Comment by stumpdk** [comment]
I should specify that only the new marker should be selected, not the tag category in general. So a click on a marker link results in just one marker on the map.

**Comment by jacobandresen** [comment]
I  think a backend function to retrieve a tag using an id would come in handy here?

**Comment by stumpdk** [comment]
That's a very important feature! Which is now implemented... :)

**Comment by stumpdk** [comment]
The zoomlevel should also adapt to the new selection when using links to markers.

**Comment by jacobandresen** [comment]
We now retrieve a single feature using id. Now only "data-id" is supported in marker links. Like this:

test <a href="#" data-id="2"> test til 2</a> (click edit to see html)

**Comment by stumpdk** [comment]
The markers already loaded should also be enabled when selecting a new marker using the link. Now, the new marker is the only visible one after click on the link.

**Comment by jacobandresen** [comment]
We now add the new marker to the existing shown group (if  it is not allready present)
