### ISSUE TITLE
en_header should be implemented

### ISSUE THREAD

**Issue by stumpdk** [jacobandresen/TagMap#27]
In the existing form, it is not possible to write headers in other languages than danish, but the content is divided in two categories. I've implemented the possibility to add english headers with the field header_en. Could this be implemented in the edit part of the TagMap?

**Comment by jacobandresen** [comment]
Sure . Can you commit the "PolleAPI" code containing the string header_en , so I can test locally ?

**Comment by stumpdk** [comment]
Sure:
CREATE TABLE `ksa_mapdata` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(150) NOT NULL,
  `header_en` varchar(150) NOT NULL,
  `content_da` text NOT NULL,
  `content_en` text,
  `geometry` text NOT NULL,
  `tags` char(250) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=MyISAM AUTO_INCREMENT=1631 DEFAULT CHARSET=utf8;

**Comment by jacobandresen** [comment]
No update  to  RequestHandler.php to transport header_en?

**Comment by stumpdk** [comment]
Oh yes, of course. Here the new version of the <a href="https://github.com/stumpdk/PolleAPI">Polle API<a/>
