### ISSUE TITLE
Get all tags and filter clientside

### ISSUE THREAD

**Issue by stumpdk** [jacobandresen/TagMap#29]
By implementing clientside filtering, the issues concerning displaying unloaded tags could be avoided. At the same time, a more strict division of gui and business logic is possible.
It would require:
1) A load function that loads all tags based on a main tag into an array.
2) A variable for each tag that indicates wheter the tag should be visible on the map or not.
3) A filter function that runs through the loaded tags and sets the visibility based on id and/or tag(s).
4) A reset filter function,that sets all tags to visible or hidden.

Is this overkill?

**Comment by jacobandresen** [comment]
This probably overkill. We can revisit this later, if needed
