### ISSUE TITLE
ux improvements on delete

### ISSUE THREAD

**Issue by jacobandresen** [jacobandresen/TagMap#9]
looks like the backend requires all fields in an object to be filled out before it works. Let's inform the user that he/she needs all fields before it will work

**Comment by jacobandresen** [comment]
looks like id,name and content_da are the only ones required

**Comment by jacobandresen** [comment]
only id should be required to delete an entry in ksa_mapdata . Note that all other data than id is irrelevant.

**Comment by jacobandresen** [comment]
The current implementation leads to that you cannot delete entries without name or content. This does not make sense. It should be possible to delete all entries with an id.

**Comment by stumpdk** [comment]
The serverside logic is now changed, so that delete requests only requires an id.
This change has not been implemented in the client side logic.

**Comment by jacobandresen** [comment]
we now only required id in the client side logic
